[Icon Theme]
Name=02-OS
Comment=02_OS Premium Glassmorphic Vector Icon Theme
Inherits=Papirus-Dark,Adwaita,hicolor
Example=02os-menu

Directories=scalable/apps,scalable/places,scalable/devices,scalable/categories,scalable/mimetypes,scalable/status,scalable/actions

[scalable/apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Context=Actions
Size=64
MinSize=16
MaxSize=512
Type=Scalable
