---
displaymanagers:
  - greetd
basicSetup: false
greetd:
    greeter_user: greeter
    greeter_group: greeter
defaultDesktopEnvironment:
    executable: /usr/local/bin/02os-gnome-session
    desktopFile: 02os-gnome
