---
defaultGroups:
    - wheel
    - audio
    - video
    - storage
    - input
    - network
    - power
    - lp
    - optical
    - rfkill
    - users
doAutologin: false
sudoersGroup: wheel
setRootPassword: false
doReusePassword: true
allowWeakPasswords: true
allowWeakPasswordsDefault: true
avoidOverlappingNames: true
userShell: /usr/bin/zsh
