u live 1000:1000 "02_OS Live User" /home/live /usr/bin/zsh
m live wheel
m live audio
m live video
m live input
m live storage
m live optical
m live network
m live lp
m live users
m live power
m live rfkill
